### ISSUE TITLE
WPML - Type Closure

### ISSUE THREAD

**Issue by thierfelder-marcus** [dev4press/debugpress#8]
As soon as WPML is installed and activated, the following error occurs.

PHP Fatal error:  Uncaught Error: Cannot use object of type Closure as array in /wp-content/plugins/debugpress/core/track/Tracker.php:694

The following bugfix would provide a remedy:
```
if ( !is_array($call['args']) || !is_array($call['args'][0]) ) {
    continue;
}
```

This must be inserted above (Tracker.php line 694)

`if ( isset( $call['args'][0][0] ) && $call['args'][0][0] instanceof Tracker )`

Maybe it would be possible to integrate this bugfix in the next update.

**Comment by dev4press** [comment]
Thanks for reporting and providing the fix. This will be added to the next minor update soon.

**Comment by thierfelder-marcus** [comment]
Thanks
